### ISSUE TITLE
Chained requires throw an exception

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/idem#11]
Something like this:
```
first thing:
  test.nop

second thing:
  test.nop:
    - require:
      - test: first thing

third thing:
  test.nop:
    - require:
      - test: second thing
```

Will throw this:
```
Traceback (most recent call last):
  File "/home/nmhughes/dev/stuff/env/bin/idem", line 8, in <module>
    sys.exit(start())
  File "/home/nmhughes/dev/stuff/env/lib/python3.6/site-packages/idem/scripts.py", line 8, in start
    hub.idem.init.cli()
  File "/home/nmhughes/dev/stuff/env/lib/python3.6/site-packages/pop/contract.py", line 131, in __call__
    return self.func(*args, **kwargs)
  File "/home/nmhughes/dev/stuff/env/lib/python3.6/site-packages/idem/idem/init.py", line 50, in cli
    hub.pop.loop.start(hub.idem.init.cli_apply())
  File "/home/nmhughes/dev/stuff/env/lib/python3.6/site-packages/pop/contract.py", line 131, in __call__
    return self.func(*args, **kwargs)
  File "/home/nmhughes/dev/stuff/env/lib/python3.6/site-packages/pop/mods/pop/loop.py", line 74, in start
    asyncio.gather(*coros)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/nmhughes/dev/stuff/env/lib/python3.6/site-packages/idem/idem/init.py", line 78, in cli_apply
    hub.OPT['idem']['test'],
  File "/home/nmhughes/dev/stuff/env/lib/python3.6/site-packages/idem/idem/init.py", line 151, in apply
    ret = await hub.idem.run.init.start(name)
  File "/home/nmhughes/dev/stuff/env/lib/python3.6/site-packages/idem/idem/run/init.py", line 27, in start
    raise Exception()
Exception
```

Versions:
```
(env) nmhughes@eitr01:~/dev/idem_azure_demo$ pip freeze | egrep 'idem|pop|rend'
idem==5
pop==7.5
rend==4.1
```

**Comment by thatch45** [comment]
some crazy oversight on my part, I was tracking the wrong dataset to ensure that it was shrinking! Thanks for the find!
